// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMMessage.proto

package com.yuhsuanzhang.him.imcommon.entity;

public final class IMMessageProto {
  private IMMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息ID，使用自增主键或雪花算法生成
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     * 消息正文
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     * 消息正文
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 senderId = 3;</code>
     * @return The senderId.
     */
    long getSenderId();

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 receiverId = 4;</code>
     * @return The receiverId.
     */
    long getReceiverId();

    /**
     * <pre>
     * 上一条消息ID
     * </pre>
     *
     * <code>int64 previousMessageId = 5;</code>
     * @return The previousMessageId.
     */
    long getPreviousMessageId();

    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>int32 receiverType = 6;</code>
     * @return The receiverType.
     */
    int getReceiverType();

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 messageType = 7;</code>
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     * @return Whether the sendTime field is set.
     */
    boolean hasSendTime();
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     * @return The sendTime.
     */
    com.google.protobuf.Timestamp getSendTime();
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     */
    com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     * @return The createTime.
     */
    com.google.protobuf.Timestamp getCreateTime();
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     * @return Whether the updateTime field is set.
     */
    boolean hasUpdateTime();
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     * @return The updateTime.
     */
    com.google.protobuf.Timestamp getUpdateTime();
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>int32 version = 11;</code>
     * @return The version.
     */
    int getVersion();
  }
  /**
   * <pre>
   *生成命令
   *protoc --java_out=./ IMMessage.proto
   * </pre>
   *
   * Protobuf type {@code com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage}
   */
  public static final class IMMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage)
      IMMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMMessage.newBuilder() to construct.
    private IMMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMMessage() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IMMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IMMessageProto.internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IMMessageProto.internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IMMessageProto.IMMessage.class, IMMessageProto.IMMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <pre>
     * 消息ID，使用自增主键或雪花算法生成
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <pre>
     * 消息正文
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息正文
     * </pre>
     *
     * <code>string content = 2;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERID_FIELD_NUMBER = 3;
    private long senderId_ = 0L;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 senderId = 3;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }

    public static final int RECEIVERID_FIELD_NUMBER = 4;
    private long receiverId_ = 0L;
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>int64 receiverId = 4;</code>
     * @return The receiverId.
     */
    @java.lang.Override
    public long getReceiverId() {
      return receiverId_;
    }

    public static final int PREVIOUSMESSAGEID_FIELD_NUMBER = 5;
    private long previousMessageId_ = 0L;
    /**
     * <pre>
     * 上一条消息ID
     * </pre>
     *
     * <code>int64 previousMessageId = 5;</code>
     * @return The previousMessageId.
     */
    @java.lang.Override
    public long getPreviousMessageId() {
      return previousMessageId_;
    }

    public static final int RECEIVERTYPE_FIELD_NUMBER = 6;
    private int receiverType_ = 0;
    /**
     * <pre>
     * 接收者类型
     * </pre>
     *
     * <code>int32 receiverType = 6;</code>
     * @return The receiverType.
     */
    @java.lang.Override
    public int getReceiverType() {
      return receiverType_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 7;
    private int messageType_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>int32 messageType = 7;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }

    public static final int SENDTIME_FIELD_NUMBER = 8;
    private com.google.protobuf.Timestamp sendTime_;
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     * @return Whether the sendTime field is set.
     */
    @java.lang.Override
    public boolean hasSendTime() {
      return sendTime_ != null;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getSendTime() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp sendTime = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
      return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp createTime_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     * @return Whether the createTime field is set.
     */
    @java.lang.Override
    public boolean hasCreateTime() {
      return createTime_ != null;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreateTime() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp createTime = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 10;
    private com.google.protobuf.Timestamp updateTime_;
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     * @return Whether the updateTime field is set.
     */
    @java.lang.Override
    public boolean hasUpdateTime() {
      return updateTime_ != null;
    }
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     * @return The updateTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdateTime() {
      return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
    }
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp updateTime = 10;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
    }

    public static final int VERSION_FIELD_NUMBER = 11;
    private int version_ = 0;
    /**
     * <pre>
     * 版本号
     * </pre>
     *
     * <code>int32 version = 11;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (senderId_ != 0L) {
        output.writeInt64(3, senderId_);
      }
      if (receiverId_ != 0L) {
        output.writeInt64(4, receiverId_);
      }
      if (previousMessageId_ != 0L) {
        output.writeInt64(5, previousMessageId_);
      }
      if (receiverType_ != 0) {
        output.writeInt32(6, receiverType_);
      }
      if (messageType_ != 0) {
        output.writeInt32(7, messageType_);
      }
      if (sendTime_ != null) {
        output.writeMessage(8, getSendTime());
      }
      if (createTime_ != null) {
        output.writeMessage(9, getCreateTime());
      }
      if (updateTime_ != null) {
        output.writeMessage(10, getUpdateTime());
      }
      if (version_ != 0) {
        output.writeInt32(11, version_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (senderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, senderId_);
      }
      if (receiverId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, receiverId_);
      }
      if (previousMessageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, previousMessageId_);
      }
      if (receiverType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, receiverType_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, messageType_);
      }
      if (sendTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getSendTime());
      }
      if (createTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getCreateTime());
      }
      if (updateTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getUpdateTime());
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IMMessageProto.IMMessage)) {
        return super.equals(obj);
      }
      IMMessageProto.IMMessage other = (IMMessageProto.IMMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getSenderId()
          != other.getSenderId()) return false;
      if (getReceiverId()
          != other.getReceiverId()) return false;
      if (getPreviousMessageId()
          != other.getPreviousMessageId()) return false;
      if (getReceiverType()
          != other.getReceiverType()) return false;
      if (getMessageType()
          != other.getMessageType()) return false;
      if (hasSendTime() != other.hasSendTime()) return false;
      if (hasSendTime()) {
        if (!getSendTime()
            .equals(other.getSendTime())) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (!getCreateTime()
            .equals(other.getCreateTime())) return false;
      }
      if (hasUpdateTime() != other.hasUpdateTime()) return false;
      if (hasUpdateTime()) {
        if (!getUpdateTime()
            .equals(other.getUpdateTime())) return false;
      }
      if (getVersion()
          != other.getVersion()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSenderId());
      hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiverId());
      hash = (37 * hash) + PREVIOUSMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPreviousMessageId());
      hash = (37 * hash) + RECEIVERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReceiverType();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      if (hasSendTime()) {
        hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + getSendTime().hashCode();
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getCreateTime().hashCode();
      }
      if (hasUpdateTime()) {
        hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateTime().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IMMessageProto.IMMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMessageProto.IMMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMessageProto.IMMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMessageProto.IMMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMessageProto.IMMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IMMessageProto.IMMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IMMessageProto.IMMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IMMessageProto.IMMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IMMessageProto.IMMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IMMessageProto.IMMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IMMessageProto.IMMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IMMessageProto.IMMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IMMessageProto.IMMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *生成命令
     *protoc --java_out=./ IMMessage.proto
     * </pre>
     *
     * Protobuf type {@code com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage)
        IMMessageProto.IMMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IMMessageProto.internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IMMessageProto.internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IMMessageProto.IMMessage.class, IMMessageProto.IMMessage.Builder.class);
      }

      // Construct using com.yuhsuanzhang.him.imcommon.entity.IMMessageProto.IMMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        content_ = "";
        senderId_ = 0L;
        receiverId_ = 0L;
        previousMessageId_ = 0L;
        receiverType_ = 0;
        messageType_ = 0;
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        createTime_ = null;
        if (createTimeBuilder_ != null) {
          createTimeBuilder_.dispose();
          createTimeBuilder_ = null;
        }
        updateTime_ = null;
        if (updateTimeBuilder_ != null) {
          updateTimeBuilder_.dispose();
          updateTimeBuilder_ = null;
        }
        version_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IMMessageProto.internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor;
      }

      @java.lang.Override
      public IMMessageProto.IMMessage getDefaultInstanceForType() {
        return IMMessageProto.IMMessage.getDefaultInstance();
      }

      @java.lang.Override
      public IMMessageProto.IMMessage build() {
        IMMessageProto.IMMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public IMMessageProto.IMMessage buildPartial() {
        IMMessageProto.IMMessage result = new IMMessageProto.IMMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(IMMessageProto.IMMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.senderId_ = senderId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.receiverId_ = receiverId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.previousMessageId_ = previousMessageId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.receiverType_ = receiverType_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.messageType_ = messageType_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.sendTime_ = sendTimeBuilder_ == null
              ? sendTime_
              : sendTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.createTime_ = createTimeBuilder_ == null
              ? createTime_
              : createTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.updateTime_ = updateTimeBuilder_ == null
              ? updateTime_
              : updateTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.version_ = version_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IMMessageProto.IMMessage) {
          return mergeFrom((IMMessageProto.IMMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IMMessageProto.IMMessage other) {
        if (other == IMMessageProto.IMMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getSenderId() != 0L) {
          setSenderId(other.getSenderId());
        }
        if (other.getReceiverId() != 0L) {
          setReceiverId(other.getReceiverId());
        }
        if (other.getPreviousMessageId() != 0L) {
          setPreviousMessageId(other.getPreviousMessageId());
        }
        if (other.getReceiverType() != 0) {
          setReceiverType(other.getReceiverType());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.hasSendTime()) {
          mergeSendTime(other.getSendTime());
        }
        if (other.hasCreateTime()) {
          mergeCreateTime(other.getCreateTime());
        }
        if (other.hasUpdateTime()) {
          mergeUpdateTime(other.getUpdateTime());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                senderId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                receiverId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                previousMessageId_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                receiverType_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                messageType_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                input.readMessage(
                    getSendTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    getCreateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                input.readMessage(
                    getUpdateTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 88: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <pre>
       * 消息ID，使用自增主键或雪花算法生成
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * 消息ID，使用自增主键或雪花算法生成
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息ID，使用自增主键或雪花算法生成
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       * 消息正文
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息正文
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息正文
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息正文
       * </pre>
       *
       * <code>string content = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息正文
       * </pre>
       *
       * <code>string content = 2;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long senderId_ ;
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 senderId = 3;</code>
       * @return The senderId.
       */
      @java.lang.Override
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 senderId = 3;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(long value) {
        
        senderId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>int64 senderId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        senderId_ = 0L;
        onChanged();
        return this;
      }

      private long receiverId_ ;
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 receiverId = 4;</code>
       * @return The receiverId.
       */
      @java.lang.Override
      public long getReceiverId() {
        return receiverId_;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 receiverId = 4;</code>
       * @param value The receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverId(long value) {
        
        receiverId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>int64 receiverId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        receiverId_ = 0L;
        onChanged();
        return this;
      }

      private long previousMessageId_ ;
      /**
       * <pre>
       * 上一条消息ID
       * </pre>
       *
       * <code>int64 previousMessageId = 5;</code>
       * @return The previousMessageId.
       */
      @java.lang.Override
      public long getPreviousMessageId() {
        return previousMessageId_;
      }
      /**
       * <pre>
       * 上一条消息ID
       * </pre>
       *
       * <code>int64 previousMessageId = 5;</code>
       * @param value The previousMessageId to set.
       * @return This builder for chaining.
       */
      public Builder setPreviousMessageId(long value) {
        
        previousMessageId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上一条消息ID
       * </pre>
       *
       * <code>int64 previousMessageId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreviousMessageId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        previousMessageId_ = 0L;
        onChanged();
        return this;
      }

      private int receiverType_ ;
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>int32 receiverType = 6;</code>
       * @return The receiverType.
       */
      @java.lang.Override
      public int getReceiverType() {
        return receiverType_;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>int32 receiverType = 6;</code>
       * @param value The receiverType to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverType(int value) {
        
        receiverType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者类型
       * </pre>
       *
       * <code>int32 receiverType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        receiverType_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>int32 messageType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp sendTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> sendTimeBuilder_;
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       * @return Whether the sendTime field is set.
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       * @return The sendTime.
       */
      public com.google.protobuf.Timestamp getSendTime() {
        if (sendTimeBuilder_ == null) {
          return sendTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        } else {
          return sendTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public Builder setSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          sendTime_ = value;
        } else {
          sendTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public Builder setSendTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (sendTimeBuilder_ == null) {
          sendTime_ = builderForValue.build();
        } else {
          sendTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public Builder mergeSendTime(com.google.protobuf.Timestamp value) {
        if (sendTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0) &&
            sendTime_ != null &&
            sendTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getSendTimeBuilder().mergeFrom(value);
          } else {
            sendTime_ = value;
          }
        } else {
          sendTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sendTime_ = null;
        if (sendTimeBuilder_ != null) {
          sendTimeBuilder_.dispose();
          sendTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public com.google.protobuf.Timestamp.Builder getSendTimeBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getSendTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getSendTimeOrBuilder() {
        if (sendTimeBuilder_ != null) {
          return sendTimeBuilder_.getMessageOrBuilder();
        } else {
          return sendTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : sendTime_;
        }
      }
      /**
       * <pre>
       * 发送时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp sendTime = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getSendTimeFieldBuilder() {
        if (sendTimeBuilder_ == null) {
          sendTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getSendTime(),
                  getParentForChildren(),
                  isClean());
          sendTime_ = null;
        }
        return sendTimeBuilder_;
      }

      private com.google.protobuf.Timestamp createTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       * @return Whether the createTime field is set.
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       * @return The createTime.
       */
      public com.google.protobuf.Timestamp getCreateTime() {
        if (createTimeBuilder_ == null) {
          return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        } else {
          return createTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public Builder setCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createTime_ = value;
        } else {
          createTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public Builder setCreateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createTimeBuilder_ == null) {
          createTime_ = builderForValue.build();
        } else {
          createTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreateTimeBuilder().mergeFrom(value);
          } else {
            createTime_ = value;
          }
        } else {
          createTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        createTime_ = null;
        if (createTimeBuilder_ != null) {
          createTimeBuilder_.dispose();
          createTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getCreateTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
        if (createTimeBuilder_ != null) {
          return createTimeBuilder_.getMessageOrBuilder();
        } else {
          return createTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        }
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp createTime = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateTimeFieldBuilder() {
        if (createTimeBuilder_ == null) {
          createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateTime(),
                  getParentForChildren(),
                  isClean());
          createTime_ = null;
        }
        return createTimeBuilder_;
      }

      private com.google.protobuf.Timestamp updateTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       * @return Whether the updateTime field is set.
       */
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       * @return The updateTime.
       */
      public com.google.protobuf.Timestamp getUpdateTime() {
        if (updateTimeBuilder_ == null) {
          return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        } else {
          return updateTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updateTime_ = value;
        } else {
          updateTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public Builder setUpdateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updateTimeBuilder_ == null) {
          updateTime_ = builderForValue.build();
        } else {
          updateTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
        if (updateTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000200) != 0) &&
            updateTime_ != null &&
            updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getUpdateTimeBuilder().mergeFrom(value);
          } else {
            updateTime_ = value;
          }
        } else {
          updateTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000200);
        updateTime_ = null;
        if (updateTimeBuilder_ != null) {
          updateTimeBuilder_.dispose();
          updateTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getUpdateTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
        if (updateTimeBuilder_ != null) {
          return updateTimeBuilder_.getMessageOrBuilder();
        } else {
          return updateTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
        }
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp updateTime = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdateTimeFieldBuilder() {
        if (updateTimeBuilder_ == null) {
          updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdateTime(),
                  getParentForChildren(),
                  isClean());
          updateTime_ = null;
        }
        return updateTimeBuilder_;
      }

      private int version_ ;
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>int32 version = 11;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>int32 version = 11;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 版本号
       * </pre>
       *
       * <code>int32 version = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000400);
        version_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage)
    }

    // @@protoc_insertion_point(class_scope:com.yuhsuanzhang.him.imcommon.entity.proto.IMMessage)
    private static final IMMessageProto.IMMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IMMessageProto.IMMessage();
    }

    public static IMMessageProto.IMMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IMMessage>
        PARSER = new com.google.protobuf.AbstractParser<IMMessage>() {
      @java.lang.Override
      public IMMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IMMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public IMMessageProto.IMMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017IMMessage.proto\022*com.yuhsuanzhang.him." +
      "imcommon.entity.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\263\002\n\tIMMessage\022\n\n\002id\030\001 \001(\003" +
      "\022\017\n\007content\030\002 \001(\t\022\020\n\010senderId\030\003 \001(\003\022\022\n\nr" +
      "eceiverId\030\004 \001(\003\022\031\n\021previousMessageId\030\005 \001" +
      "(\003\022\024\n\014receiverType\030\006 \001(\005\022\023\n\013messageType\030" +
      "\007 \001(\005\022,\n\010sendTime\030\010 \001(\0132\032.google.protobu" +
      "f.Timestamp\022.\n\ncreateTime\030\t \001(\0132\032.google" +
      ".protobuf.Timestamp\022.\n\nupdateTime\030\n \001(\0132" +
      "\032.google.protobuf.Timestamp\022\017\n\007version\030\013" +
      " \001(\005B<\n*com.yuhsuanzhang.him.imcommon.en" +
      "tity.protoB\016IMMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yuhsuanzhang_him_imcommon_entity_proto_IMMessage_descriptor,
        new java.lang.String[] { "Id", "Content", "SenderId", "ReceiverId", "PreviousMessageId", "ReceiverType", "MessageType", "SendTime", "CreateTime", "UpdateTime", "Version", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
